spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatistest config
mybatis:
  mapper-locations: classpath:/mapper/*.xml
